@echo off
cd /d "%~dp0"

set ACP_AUTO_UPDATE=0
set ACP_DEBUG=1

set BILI_WORKFLOW_ENABLED=1
set BILI_WORKFLOW_PHASE_GC=1
set BILI_WORKFLOW_SESSION_GC=1
set BILI_WORKFLOW_REREAD_AFTER_PHASE=1
set BILI_WORKFLOW_PRUNER=1
set BILI_WORKFLOW_ARCHIVE_RAW=1

start http://127.0.0.1:8787/__bili/

node dist/index.js

pause
