@echo off
cd /d "%~dp0"

set ACP_AUTO_UPDATE=0
set ACP_DEBUG=1

set BILI_WORKFLOW_ENABLED=1
set BILI_WORKFLOW_PHASE_GC=1
set BILI_WORKFLOW_SESSION_GC=1
set BILI_WORKFLOW_REREAD_AFTER_PHASE=1
set BILI_WORKFLOW_PRUNER=1
set BILI_WORKFLOW_ARCHIVE_RAW=1

set BILI_WORKFLOW_CHEAP_MODEL_ENABLED=0
set BILI_WORKFLOW_HISTORIAN_ENABLED=0

node dist/index.js

pause