import { WEB_CLIENT } from "./client.js";
import { WEB_STYLES } from "./styles.js";

const INFO_ICON = `<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="9"></circle><path d="M12 16v-4"></path><path d="M12 8h.01"></path></svg>`;

export function renderPage(origin: string, version: string): string {
    return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>billion-context</title><style>${WEB_STYLES}</style></head><body>
<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-title">billion<span>-context</span></div><div class="version">v${version}</div></div><a class="fork-ribbon" href="https://github.com/ranxianglei/billion-context" target="_blank" rel="noopener">★ Fork me on GitHub</a><nav class="nav"><button class="active" data-page="overview">概览</button><button data-page="routing">接入</button><button data-page="upstream">上游</button><button data-page="sessions">会话</button><button data-page="context">上下文</button><button data-page="settings">设置</button></nav></aside>
<main class="main"><section id="page-overview" class="page active"><h1>概览</h1><p class="lead">本地路由与上游网络相互独立，ACP 压缩运行在两者之间。</p><div class="grid"><div class="card"><h2>服务地址</h2><p class="mono">${origin}</p></div><div class="card"><h2>客户端接入</h2><p class="status">在"接入"页将各客户端（Codex / Claude Code / OpenCode / Pi 等）的流量路由到 bili。</p></div></div></section>
<section id="page-routing" class="page"><h1>客户端接入</h1><p class="lead">两类接入：A. 推荐接入方式（<span class="mono">/bili/</span> 前缀，零配置）；B. 证书接入方式（MITM，需信任 CA 证书）。</p>
<h2 class="section-title">A. 推荐接入方式（/bili/ 前缀）</h2>
<p class="hint">在客户端配置里把原 baseURL 前加上 <span class="mono">${origin}/bili/</span> 即可，其余不变。</p>
<div class="card"><div class="card-head"><h2>OpenCode</h2><button class="btn small copy-btn" data-copy="${origin}/bili/https://open.bigmodel.cn/api/coding/paas/v4">复制</button></div><dl class="kv"><dt>配置文件</dt><dd class="mono">~/.config/opencode/opencode.json</dd><dt>baseURL</dt><dd class="mono">${origin}/bili/https://open.bigmodel.cn/api/coding/paas/v4</dd></dl></div>
<div class="card"><div class="card-head"><h2>Codex（API key）</h2><button class="btn small copy-btn" data-copy="${origin}/bili/https://api.openai.com/v1">复制</button></div><dl class="kv"><dt>配置文件</dt><dd class="mono">~/.codex/config.toml</dd><dt>base_url</dt><dd class="mono">${origin}/bili/https://api.openai.com/v1</dd></dl></div>
<div id="codex-chatgpt-card" class="card codex-toggle-card" tabindex="0" data-codex-toggle><div class="card-head"><h2>Codex（ChatGPT 登录）</h2><div class="card-actions"><span id="codex-config-status" class="badge"></span><button class="btn small copy-btn" data-copy="model_provider = &quot;openai&quot;&#10;openai_base_url = &quot;${origin}/bili/https://chatgpt.com/backend-api/codex&quot;">复制配置</button></div></div><dl class="kv"><dt>配置文件</dt><dd class="mono">~/.codex/config.toml</dd><dt>配置</dt><dd class="mono">model_provider = "openai"<br>openai_base_url = "${origin}/bili/https://chatgpt.com/backend-api/codex"</dd><dt>认证</dt><dd><span class="mono">codex login</span>（OAuth token 透传，无需证书）</dd></dl></div>
<div class="card"><div class="card-head"><h2>Claude Code（API key）</h2><button class="btn small copy-btn" data-copy="${origin}/bili/https://api.anthropic.com">复制</button></div><dl class="kv"><dt>环境变量</dt><dd class="mono">ANTHROPIC_BASE_URL=${origin}/bili/https://api.anthropic.com</dd></dl></div>
<div class="card"><div class="card-head"><h2>Pi</h2><span class="badge">不推荐</span><button class="btn small copy-btn" data-copy="${origin}/bili/https://api.anthropic.com">复制</button></div><dl class="kv"><dt>配置文件</dt><dd class="mono">~/.pi/agent/models.json</dd><dt>baseUrl</dt><dd class="mono">${origin}/bili/https://api.anthropic.com</dd></dl><p class="hint">⚠️ 不推荐：Pi 的 session 管理与 bili 压缩状态存在冲突，详见 README。</p></div>
<div class="card"><div class="card-head"><h2>其他（Cursor / Aider / Continue）</h2><button class="btn small copy-btn" data-copy="${origin}/bili/">复制</button></div><dl class="kv"><dt>规则</dt><dd>任意 baseURL 前加 <span class="mono">${origin}/bili/</span></dd><dt>示例</dt><dd class="mono">${origin}/bili/https://api.openai.com/v1</dd></dl></div>
<h2 class="section-title">B. 证书接入方式（zcode 等类型）</h2>
<p class="hint">不支持改 URL 的客户端（endpoint 硬编码）需 MITM 透明代理，设 HTTPS_PROXY + 信任 CA 证书。</p>
<div class="card"><div class="card-head"><h2>ZCode（编程套餐）</h2><span class="badge">MITM</span></div><dl class="kv"><dt>方式</dt><dd>MITM 透明代理</dd><dt>设置</dt><dd>Settings → Network → HTTP Proxy = <span class="mono">${origin}</span></dd><dt>CA 证书</dt><dd class="mono">~/.local/share/billion-context/ca/root-ca.pem</dd></dl></div></section>
<section id="page-upstream" class="page"><h1>上游网络</h1><p class="lead">控制 bili 如何访问真实 Provider，不会改变客户端的本地路由地址。</p><div class="card"><div class="card-head"><h2>全局代理</h2></div><div class="modes"><label><input type="radio" name="proxy-mode" value="direct" checked>直连（默认）</label><label><input type="radio" name="proxy-mode" value="manual">手动代理</label><label><input type="radio" name="proxy-mode" value="auto">自动（跟随系统）</label></div><div class="field"><label>HTTP / HTTPS Proxy</label><input id="proxy-url" class="mono" placeholder="http://127.0.0.1:7897"></div><dl class="kv"><dt>当前来源</dt><dd id="upstream-source">直连</dd><dt>有效代理</dt><dd id="upstream-effective" class="mono">direct</dd><dt>系统 PAC</dt><dd id="upstream-pac" class="mono">—</dd><dt>状态</dt><dd id="upstream-state" class="status">尚未测试</dd></dl><div class="actions"><button id="save-upstream" class="btn primary">保存并热更新</button><button id="test-upstream" class="btn">测试连接</button></div></div><div class="card"><div class="card-head"><h2>按 URL 覆盖</h2></div><p class="status">为特定 Provider 单独设置上游代理，覆盖全局设置。留空 = 继承全局。</p><div id="upstream-overrides" class="status">加载中</div><div class="actions"><button id="save-overrides" class="btn primary">保存覆盖并热更新</button></div></div></section>
<section id="page-sessions" class="page"><div class="card-head"><div><h1>会话</h1><p class="lead">ACP 压缩状态与上游用量。</p></div><button id="refresh-sessions" class="btn">刷新</button></div><div class="card"><table><thead><tr><th>标题</th><th>协议</th><th>标识</th><th>请求</th><th>上下文</th><th>最后活动</th></tr></thead><tbody id="sessions-body"></tbody></table></div></section>
<section id="page-context" class="page"><div class="card-head"><div><h1>上下文管理</h1><p class="lead">Codex 优先的输出压缩、Project Memory、Repo Bridge 与缓存感知调度。</p></div><button id="refresh-workflow" class="btn">刷新状态</button></div>
<div id="workflow-runtime-summary" class="metric-grid"><div class="metric"><span>运行状态</span><strong>加载中</strong></div></div>
<div class="card"><div class="card-head"><div class="title-with-help"><h2>Workflow 核心</h2><button class="info-tip" type="button" aria-label="Workflow 核心说明" data-tooltip="管理上下文生命周期：阶段回收、会话记忆、强制重读和确定性输出压缩">${INFO_ICON}</button></div><span class="badge ok">Codex first</span></div><div class="toggle-grid"><label class="toggle"><input id="workflow-enabled" type="checkbox"><span>启用上下文管理</span></label><label class="toggle"><input id="workflow-phase-gc" type="checkbox"><span>Phase GC</span></label><label class="toggle"><input id="workflow-session-gc" type="checkbox"><span>Session / Project Memory</span></label><label class="toggle"><input id="workflow-reread" type="checkbox"><span>Phase 后强制重读</span></label><label class="toggle"><input id="workflow-archive" type="checkbox"><span>归档语义原文</span></label><label class="toggle"><input id="pruner-enabled" type="checkbox"><span>确定性输出压缩</span></label></div><div class="form-grid"><div class="field"><label>目标上下文比例</label><input id="workflow-target-ratio" type="number" min="0.01" max="1" step="0.01"></div><div class="field"><label>Rollover 最小 token</label><input id="workflow-rollover-min" type="number" min="1" step="1000"></div><div class="field"><label>Memory 注入 token 上限</label><input id="workflow-memory-max" type="number" min="1" step="1000"></div><div class="field"><label>Project 历史 Session 数</label><input id="workflow-project-sessions" type="number" min="1"></div><div class="field"><label>确定性 Pruner 阈值</label><input id="pruner-min" type="number" min="1" step="500"></div></div></div>
<div class="grid"><div class="card"><div class="card-head"><div class="title-with-help"><h2>输出压缩模型</h2><button class="info-tip" type="button" aria-label="输出压缩模型说明" data-tooltip="只为大型工具输出做轻量压缩，减少上下文占用；不读取源码，也不替你做工程决策。">${INFO_ICON}</button></div><span id="cheap-model-status" class="badge">未启用</span></div><p class="hint">Cheap Pruner 只处理确定性提取器无法压缩的大型 Tool Output，不读取源码，也不做工程决策。</p><label class="toggle"><input id="cheap-enabled" type="checkbox"><span>启用 Cheap Pruner</span></label><div class="field"><label>OpenAI-compatible Endpoint</label><input id="cheap-endpoint" class="mono" placeholder="http://127.0.0.1:11434/v1/chat/completions"></div><div class="field"><label>Model</label><input id="cheap-model" class="mono" placeholder="qwen3:4b"></div><div class="field"><label>API Key（留空保留当前值）</label><input id="cheap-api-key" type="password" autocomplete="new-password" placeholder="未配置"></div><label class="toggle danger-check"><input id="cheap-clear-key" type="checkbox"><span>清除已保存的 API Key</span></label><div class="form-grid"><div class="field"><label>触发阈值</label><input id="cheap-min" type="number" min="1"></div><div class="field"><label>最大输出 token</label><input id="cheap-max" type="number" min="1"></div><div class="field"><label>超时 ms</label><input id="cheap-timeout" type="number" min="1"></div></div></div>
<div class="card"><div class="card-head"><div class="title-with-help"><h2>Cheap Historian</h2><button class="info-tip" type="button" aria-label="Historian 说明" data-tooltip="读取受限的结构化 checkpoint，生成辅助叙事；不会覆盖确定性事实，也不会接收完整原始会话。">${INFO_ICON}</button></div><span id="historian-status" class="badge">未启用</span></div><p class="hint">只读取受限的结构化 checkpoint，生成附加叙事；不会覆盖确定性事实层，也不会接收完整原始会话。</p><label class="toggle"><input id="historian-enabled" type="checkbox"><span>启用 Historian</span></label><div class="field"><label>OpenAI-compatible Endpoint</label><input id="historian-endpoint" class="mono" placeholder="可与输出压缩模型共用"></div><div class="field"><label>Model</label><input id="historian-model" class="mono" placeholder="可与输出压缩模型共用"></div><div class="field"><label>API Key（留空保留当前值）</label><input id="historian-api-key" type="password" autocomplete="new-password" placeholder="未配置"></div><label class="toggle danger-check"><input id="historian-clear-key" type="checkbox"><span>清除已保存的 API Key</span></label><div class="form-grid"><div class="field"><label>最大输入 token</label><input id="historian-input" type="number" min="1"></div><div class="field"><label>最大输出 token</label><input id="historian-output" type="number" min="1"></div><div class="field"><label>超时 ms</label><input id="historian-timeout" type="number" min="1"></div></div></div></div>
<div class="grid"><div class="card"><div class="card-head"><div class="title-with-help"><h2>Repo Bridge</h2><button class="info-tip" type="button" aria-label="Repository Bridge 说明" data-tooltip="连接当前工作区的 Git 状态，确保修改前的文件已经被重新读取，避免基于过期内容写入。">${INFO_ICON}</button></div><span class="badge">强一致性</span></div><div class="toggle-grid"><label class="toggle"><input id="repo-enabled" type="checkbox"><span>启用 Repository Bridge</span></label><label class="toggle"><input id="repo-reread" type="checkbox"><span>Phase 后要求重新读取</span></label></div><div class="field"><label>Workspace Root（留空自动发现）</label><input id="repo-root" class="mono" placeholder="自动发现"></div><div class="form-grid"><div class="field"><label>Hash 最大字节</label><input id="repo-hash-max" type="number" min="1"></div><div class="field"><label>Git 超时 ms</label><input id="repo-timeout" type="number" min="1"></div></div></div>
<div class="card"><div class="card-head"><div class="title-with-help"><h2>Cache-aware Scheduler</h2><button class="info-tip" type="button" aria-label="Cache-aware Scheduler 说明" data-tooltip="根据缓存命中率、上下文增长和重写成本，决定何时延后回收或执行上下文 rollover。">${INFO_ICON}</button></div><span class="badge">Deferred GC</span></div><div class="form-grid"><div class="field"><label>保护 cache hit ratio</label><input id="cache-hit" type="number" min="0.01" max="1" step="0.01"></div><div class="field"><label>高增长率</label><input id="cache-growth" type="number" min="0.01" max="1" step="0.01"></div><div class="field"><label>每步预计 token</label><input id="cache-step" type="number" min="1"></div><div class="field"><label>后续工作 token 上限</label><input id="cache-max-next" type="number" min="1"></div><div class="field"><label>Debug 窗口 operations</label><input id="cache-debug-window" type="number" min="1"></div><div class="field"><label>Rewrite cost 权重</label><input id="cache-rewrite" type="number" min="0.01" max="10" step="0.1"></div></div></div></div>
<div class="card"><div class="card-head"><h2>会话 Telemetry</h2><span class="badge">最近 8 个</span></div><div class="table-scroll"><table><thead><tr><th>项目 / 仓库</th><th>Task / Phase</th><th>Cache</th><th>Scheduler</th><th>预裁剪节省</th><th>Repo Guard</th></tr></thead><tbody id="workflow-sessions-body"></tbody></table></div></div>
<div class="actions sticky-actions"><button id="save-workflow" class="btn primary">保存并热更新上下文设置</button><span id="workflow-save-note" class="status">API Key 不会在读取配置时返回。</span></div></section>
<section id="page-settings" class="page"><h1>高级设置</h1><p class="lead">直接编辑 providers JSON（添加新 Provider、配置模型上下文窗口、按 URL 代理等）；保存后立即热更新。</p><div class="card"><div class="field"><label>providers JSON</label><textarea id="providers-json">{}</textarea></div><div class="actions"><button id="save-providers" class="btn primary">保存并应用</button></div></div></section></main></div><div id="toast" class="toast"></div><script>${WEB_CLIENT}</script></body></html>`;
}
